# Model ID (HuggingFace models).
model_id: "sentence-transformers/all-MiniLM-L12-v2"

# Accepted values: 'retrieval', 'reranking'
task_to_evaluate: "retrieval"

# Corpus jsonl file path with records - <id,title,text>.
corpus_path: "resources/corpus.jsonl"

# Queries jsonl file path with records - <id,text>.
queries_path: "resources/queries.jsonl"

# Candidates jsonl file path with records - <query_id,doc_id,rating>.
candidates_path: "resources/candidates.jsonl"

# Relevance scale used in candidates dataset for rating field
# Accepted values:
#   - binary: 0 (not relevant), 1 (relevant)
#   - graded: 0 (not relevant), 1 (maybe ok), 2 (thatâ€™s my result)
relevance_scale: "graded"

# (Optional) Path to write mteb resources, if not given it will be written to resources dir in the root folder
output_dest: "resources"

# (Optional) Path to write mteb document and query embeddings, if not given it will be written to resources/embeddings dir
embeddings_dest: "resources/embeddings"

